program:
  CEL.kernel.main
#method: grid
method: random
name: LV2_V2F2LO2_lf2_IRM
parameters:
  config:
    values:
      - configs/json_config/LotkaVolterra2/IRM.yaml
  'exp.init_args.dataloader.init_args.dataset.init_args.diff_friction':
    value: [ value2, fight2, limited, omnivore2, none ]
  'exp.init_args.dataloader.init_args.dataset.init_args.input_length_factor':
    value: 2
  'exp.init_args.model.init_args.depth_enc':
    values: [2] #[2, 4]
  'exp.init_args.model.init_args.dfunc_hidden_channels':
    values: [32] #[32, 64]
  'exp.init_args.model.init_args.func_embedding_channels':
    values: [ 32, 64 ] #[16, 64 ]
  'exp.init_args.model.init_args.hyper_hidden_channels':
    values: [ 64] #[16, 64 ]
  'exp.init_args.model.init_args.hyper_mlp_depth':
    values: [ 4] #[16, 64 ]
  'exp.init_args.lr':
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-3
  'exp.init_args.lambda_reg':
    distribution: log_uniform_values
    min: 1e-2
    max: 1e2
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - ${args}