program:
  CEL.kernel.main
#method: grid
method: random
name: LV2_V2F2LO2_lf2_MAML
parameters:
  config:
    values:
      - configs/json_config/LotkaVolterra2/MAML.yaml
  'exp.init_args.dataloader.init_args.dataset.init_args.diff_friction':
    value: [ value2, fight2, limited, omnivore2, none ]
  'exp.init_args.dataloader.init_args.dataset.init_args.input_length_factor':
    value: 2
  'exp.init_args.model.init_args.depth_enc':
    values: [2] #[2, 4]
  'exp.init_args.model.init_args.dfunc_hidden_channels':
    values: [32] #[32, 64]
  'exp.init_args.lr':
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-3
  'exp.init_args.model.init_args.lr':
    distribution: log_uniform_values
    min: 1e-3
    max: 1e0
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - ${args}