program:
  CEL.kernel.main
#method: grid
method: random
name: Pendulum_ETSD_MAML
parameters:
  config:
    values:
      - configs/json_config/DampedPendulum/MAML.yaml
  'exp.init_args.dataloader.init_args.dataset.init_args.diff_friction':
    value: [energy, thick_air, spring, damped, none]
  'exp.init_args.model.init_args.depth_enc':
    values: [2] #[2, 4]
  'exp.init_args.model.init_args.dfunc_hidden_channels':
    values: [32] #[32, 64]
  'exp.init_args.lr':
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-3
  'exp.init_args.model.init_args.lr':
    distribution: log_uniform_values
    min: 1e-3
    max: 1e0
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - ${args}