program:
  CEL.kernel.main
#method: grid
method: random
name: SIR_FOND_VREx
parameters:
  config:
    values:
      - configs/json_config/SIREpidemic/VREx.yaml
  'exp.init_args.dataloader.init_args.dataset.init_args.diff_friction':
    value: [ fake, orig, new, dead, none ]
  'exp.init_args.dataloader.init_args.dataset.init_args.input_length_factor':
    value: 3
  'exp.init_args.model.init_args.depth_enc':
    values: [ 1, 2 ] #[2, 4]
  'exp.init_args.model.init_args.dfunc_hidden_channels':
    values: [ 16, 32 ] #[32, 64]
  'exp.init_args.model.init_args.func_embedding_channels':
    values: [ 32 ] #[16, 64 ]
  'exp.init_args.model.init_args.hyper_hidden_channels':
    values: [ 32 ] #[16, 64 ]
  'exp.init_args.model.init_args.hyper_mlp_depth':
    values: [ 3 ]
  'exp.init_args.lr':
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-3
  'exp.init_args.lambda_reg':
    distribution: log_uniform_values
    min: 1e-1
    max: 1e3
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - ${args}