exp:
  class_path: InvariantFuncExperiment
  init_args:
    weight_decay: 0.
    lr: 1e-3
    max_epoch: 100
    ctn_epoch: 0
    device: 0
    log_interval: 1
    wandb_logger: True
    DEBUG: False
    num_sampling_per_batch: 10
    partial_eval: False
    lambda_inv: 1
    lambda_side: 0
    inv_type: None
    inference_out: inv
    adapt_steps: 100
    adapt_lr: 1e-2
    model:
      class_path: InvariantFunc
      init_args:
        y_channels: 2
        W_channels: 2
        dfunc_hidden_channels: 64
        hyper_hidden_channels: 64
        depth_enc: 2
        num_envs: 4
    dataloader: dataset.yaml
name: '{cfg.exp.model.dfunc_hidden_channels}+{cfg.exp.model.hyper_hidden_channels}_{cfg.exp.model.depth_enc}_{cfg.exp.adapt_steps}x{cfg.exp.adapt_lr}'
#tags:
#  - InvariantFunc