exp:
  class_path: InvariantFuncEncExperiment
  init_args:
    weight_decay: 0.
    lr: 1e-3
    max_epoch: 1000 # No num_sampling_per_batch for IFE, therefore, more epochs needed.
    ctn_epoch: 0
    device: 0
    log_interval: 1
    wandb_logger: True
    DEBUG: False
    num_sampling_per_batch: 10
    partial_eval: False
    lambda_inv: 1
    lambda_env_dis: 1
    lambda_reverse: 0.01
    inv_type: VREx
    inference_out: inv
    adapt_steps: 100
    adapt_lr: 1e-2
    model:
      class_path: InvariantFuncEnc
      init_args:
        y_channels: 2
        W_channels: 2
#        dfunc_hidden_channels: 256
        dfunc_hidden_channels: 64
#        hyper_hidden_channels: 256
        hyper_hidden_channels: 32
#        depth_enc: 4
        depth_enc: 2
        num_envs: 4
    dataloader: dataset.yaml
name: 'df{cfg.exp.model.dfunc_hidden_channels}x{cfg.exp.model.depth_enc}+h{cfg.exp.model.hyper_hidden_channels}/{cfg.exp.inv_type}{cfg.exp.lambda_inv}_D{cfg.exp.lambda_reverse}|W{cfg.exp.model.W_channels}'
#tags:
#  - InvariantFunc