name: CEL
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch==2.1.2
  - torchvision==0.16.2
  - torchaudio==2.1.2
  - pytorch-cuda=11.8
  - jaxlib[build=*cuda*]
  - jax==0.4.23
  - optax
  - diffrax
  - equinox
  - cuda-nvcc=11.8
  - scikit-learn
  - jupyterlab
  - pysr
  - tqdm
  - matplotlib
  - scipy=1.11
  - jsonnet
  - cmake
  - pip
  - pip:
      - munch
      - ruamel.yaml
      - typed-argument-parser
      - pynvml
      - psutil
      - jsonargparse[all]
#      - jax==0.4.23
      - torchdiffeq
      - docopt
      - pysindy
      - sympy2jax
      - wandb
      - python-dotenv
      - cilog
      - einops
      - torch_scatter
      - --find-links https://data.pyg.org/whl/torch-2.1.0+cu118.html
